'use client';
import { useEffect, useState } from 'react';
import type { Schedule, ServiceConfig } from '../../../src/domain';
const money=(v:number|string)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(v)/100);
const local=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'});
const weekly:Schedule={weekly:Object.fromEntries(Array.from({length:7},(_,i)=>[String(i),[]]))};
const emptyService={id:'',name:'',published:false,poolId:null as string|null,config:{priceType:'fixed',priceSatang:0,min:1,max:1,setupMinutes:0,cleanupMinutes:0,leadMinutes:0,allowedSpaces:[],description:'',image:'',video:'',poster:''} as ServiceConfig};
const t=(n:number)=>String(Math.floor(n/60)%24).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const minutes=(s:string)=>{const [h,m]=s.split(':').map(Number);return h*60+m;};
export default function OperationsPage(){
 const [mode,setMode]=useState('loading'),[who,setWho]=useState<any>(null),[token,setToken]=useState(''),[tab,setTab]=useState('catalog');
 const [data,setData]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[spaces,setSpaces]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [service,setService]=useState(structuredClone(emptyService)),[unit,setUnit]=useState<any>(null),[pool,setPool]=useState({id:'',name:'',kind:'inventory',count:1});
 const [venue,setVenue]=useState<any>(null);
 const [account,setAccount]=useState({email:'',role:'manager',unitId:'',active:true});
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(d=>{const m=d.adminMode==='access'?'access':d.mode==='development-sandbox'?'sandbox':'setup';setMode(m);}).catch(()=>setMode('setup'));},[]);
 async function call(path:string,body?:unknown){const r=await fetch('/api/admin/'+path,{method:body===undefined?'GET':'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error?.replaceAll('_',' ')??'Request failed');return d;}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function load(next=tab,identity=who){setData(await call(next==='catalog'?'catalog':next==='staff'?'staff':next==='tasks'?'assignments':next));if(identity.role!=='staff'){setStaff(await call('staff'));setSpaces(await call('spaces'));}}
 async function connect(){await run(async()=>{const identity=await call('me');setWho(identity);const next=identity.role==='staff'?'tasks':'catalog';setTab(next);await load(next,identity);});}
 async function save(path:string,value:unknown,message='Saved.'){await call(path,value);await load();setNotice(message);}
 function config(key:keyof ServiceConfig,value:unknown){setService(s=>({...s,config:{...s.config,[key]:value}}));}
 function shifts(){const schedule:Schedule=unit.shifts??structuredClone(weekly);return <>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=>{const key=String(i),ws=schedule.weekly[key]??[];const change=(windows:any[])=>setUnit({...unit,shifts:{...schedule,weekly:{...schedule.weekly,[key]:windows}}});return <section className="hours-editor" key={day}><h3>{day}</h3>{!ws.length&&<small>Off shift</small>}{ws.map((w,j)=><div className="row" key={j}><label>From<input type="time" value={t(w.start)} onChange={e=>change(ws.map((v,k)=>k===j?{...v,start:minutes(e.target.value)}:v))}/></label><label>Until<input type="time" value={t(w.end)} onChange={e=>change(ws.map((v,k)=>k===j?{...v,end:minutes(e.target.value)+(v.end>=1440?1440:0)}:v))}/></label><label className="agree"><input type="checkbox" checked={w.end>=1440} onChange={e=>change(ws.map((v,k)=>k===j?{...v,end:v.end%1440+(e.target.checked?1440:0)}:v))}/>Ends next day</label><button onClick={()=>change(ws.filter((_,k)=>k!==j))}>Remove window</button></div>)}<button onClick={()=>change([...ws,{start:540,end:1080}])}>Add shift window</button></section>;})}</>;}
 return <><header><a href="/">224<span>LIVE HOUSE</span></a><a href="/admin">Schedule</a></header><main className="operations"><h1>Venue operations</h1><p>Catalog, team assignments and payment records. Times use Asia/Bangkok.</p>
 {mode==='setup'?<section className="panel"><h2>Connect your venue</h2><p>The operations screens are built. Live editing needs PostgreSQL and Cloudflare Access with MFA enabled for your team.</p><p>Customer payments remain closed until a payment provider is connected.</p><a href="/admin">View schedule administration</a></section>:<>
 {!who?<section className="panel"><h2>{mode==='access'?'Team sign-in':'Development admin'}</h2>{mode==='sandbox'&&<label>Development API token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label>}<button className="primary" disabled={busy||(mode==='sandbox'&&token.length<32)} onClick={connect}>{mode==='access'?'Continue with your MFA session':'Connect'}</button></section>:<>
 <section className="panel"><p>{who.email} · {who.role}</p>{mode==='access'?<a href="/cdn-cgi/access/logout">Sign out</a>:<button onClick={()=>{setWho(null);setToken('');setData([]);setStaff([]);setSpaces([]);}}>Disconnect</button>}</section>
 <nav className="admin-tabs" aria-label="Operations sections">{(who.role==='staff'?['tasks']:who.role==='owner'?['spaces','catalog','staff','tasks','bookings','payments','accounts','audit']:['catalog','staff','tasks','bookings','payments']).map(name=><button aria-current={tab===name?'page':undefined} disabled={busy} key={name} onClick={()=>run(async()=>{setTab(name);await load(name);})}>{({spaces:'Venue & rates',catalog:'Services',staff:'Staff & stock',tasks:'Assignments',bookings:'Bookings',payments:'Payments',accounts:'Team access',audit:'Audit log'} as any)[name]}</button>)}</nav>
 <button disabled={busy} onClick={()=>run(()=>load())}>Refresh records</button>
 {tab==='spaces'&&<div className="columns"><section className="panel"><h2>Venue & rates</h2><button onClick={()=>setVenue({id:'',name:'',capacity:1,published:false,config:{baseSatang:0,otSatang:0,maxHours:2,slotMinutes:30,setupMinutes:0,cleanupMinutes:0,leadMinutes:0,horizonDays:90,holdMinutes:10,policyVersion:'',rules:'',schedule:structuredClone(weekly)}})}>New space</button>{data.map(s=><article className="service" key={s.id}><h3>{s.name}</h3><p>{s.capacity} guests · {s.published?'Published':'Draft'}</p><button onClick={()=>setVenue(structuredClone(s))}>Edit venue</button></article>)}</section><section className="panel"><h2>Venue settings</h2>{venue?<><label>Space ID<input value={venue.id} onChange={e=>setVenue({...venue,id:e.target.value})}/></label><label>Space name<input value={venue.name} onChange={e=>setVenue({...venue,name:e.target.value})}/></label><label>Guest capacity<input type="number" min="1" value={venue.capacity} onChange={e=>setVenue({...venue,capacity:Number(e.target.value)})}/></label>{(['baseSatang','otSatang'] as const).map(key=><label key={key}>{key==='baseSatang'?'Base rate per hour (THB)':'OT per hour (THB)'}<input type="number" min="0.01" step="0.01" value={venue.config[key]/100} onChange={e=>setVenue({...venue,config:{...venue.config,[key]:Math.round(Number(e.target.value)*100)}})}/></label>)}<p>Minimum booking: 2 hours. Extra hours use the OT rate.</p>{Object.entries({maxHours:'Maximum hours',slotMinutes:'Start interval (minutes)',setupMinutes:'Setup buffer (minutes)',cleanupMinutes:'Cleanup buffer (minutes)',leadMinutes:'Advance notice (minutes)',horizonDays:'Booking horizon (days)',holdMinutes:'Hold duration (minutes)'}).map(([key,label])=><label key={key}>{label}<input type="number" value={venue.config[key]} onChange={e=>setVenue({...venue,config:{...venue.config,[key]:Number(e.target.value)}})}/></label>)}<label>Policy version<input value={venue.config.policyVersion} onChange={e=>setVenue({...venue,config:{...venue.config,policyVersion:e.target.value}})}/></label><label>Rules and accepted payment/cancellation terms<textarea value={venue.config.rules} onChange={e=>setVenue({...venue,config:{...venue.config,rules:e.target.value}})}/></label><label className="agree"><input type="checkbox" checked={venue.published} onChange={e=>setVenue({...venue,published:e.target.checked})}/>Published</label><button className="primary" disabled={busy||!venue.id||!venue.name} onClick={()=>run(async()=>{const r=await call('spaces',venue);await load();setNotice('Venue saved. '+r.reviewBookings.length+' existing booking(s) to review.');})}>Save venue</button><a href="/admin">Edit opening hours</a></>:<p>Select or create a venue. New spaces start closed until you set opening hours.</p>}</section></div>}
 {tab==='catalog'&&<div className="columns"><section className="panel"><h2>Additional services</h2><button onClick={()=>setService(structuredClone(emptyService))}>New service</button>{data.map(s=><article className="service" key={s.id}>{s.config.image&&<img loading="lazy" src={s.config.image} alt={s.name}/>}<h3>{s.name}</h3><p>{s.published?'Published':'Draft'} · {s.config.priceType==='request_quote'?'Request quote':money(s.config.priceSatang)+' / '+s.config.priceType}</p><button onClick={()=>setService({...s,poolId:s.pool_id})}>Edit service</button></article>)}</section><section className="panel"><h2>Service details</h2><label>Service ID<input value={service.id} onChange={e=>setService({...service,id:e.target.value})}/></label><label>Name<input value={service.name} onChange={e=>setService({...service,name:e.target.value})}/></label><label>Description / inclusions<textarea value={service.config.description??''} onChange={e=>config('description',e.target.value)}/></label><label>Price model<select value={service.config.priceType} onChange={e=>config('priceType',e.target.value)}>{['fixed','unit','hour','request_quote'].map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Price (THB)<input type="number" min="0" step="0.01" value={service.config.priceSatang/100} onChange={e=>config('priceSatang',Math.round(Number(e.target.value)*100))}/></label>
 {(['min','max','leadMinutes','setupMinutes','cleanupMinutes'] as const).map(key=><label key={key}>{({min:'Minimum quantity',max:'Maximum quantity',leadMinutes:'Lead time (minutes)',setupMinutes:'Setup (minutes)',cleanupMinutes:'Cleanup (minutes)'})[key]}<input type="number" min="0" value={service.config[key]} onChange={e=>config(key,Number(e.target.value))}/></label>)}
 <label>Capacity pool<select value={service.poolId??''} onChange={e=>setService({...service,poolId:e.target.value||null})}><option value="">No limited resource</option>{[...new Map(staff.map(u=>[u.pool_id,u])).values()].map(u=><option key={u.pool_id} value={u.pool_id}>{u.name} ({u.kind})</option>)}</select></label>
 <fieldset><legend>Available spaces</legend>{spaces.map(s=><label className="agree" key={s.id}><input type="checkbox" checked={service.config.allowedSpaces.includes(s.id)} onChange={e=>config('allowedSpaces',e.target.checked?[...service.config.allowedSpaces,s.id]:service.config.allowedSpaces.filter(v=>v!==s.id))}/>{s.name}</label>)}</fieldset>
 {(['image','video','poster'] as const).map(key=><label key={key}>{key==='image'?'Cover image URL':key==='video'?'Optional video URL':'Video poster URL'}<input type="url" value={service.config[key]??''} onChange={e=>config(key,e.target.value)}/></label>)}<small>Use published media from your authorized storage. Video plays only on request.</small><label className="agree"><input type="checkbox" checked={service.published} onChange={e=>setService({...service,published:e.target.checked})}/>Published</label><button className="primary" disabled={busy||!service.id||!service.name} onClick={()=>run(()=>save('services',service))}>Save service</button></section></div>}
 {tab==='staff'&&<div className="columns"><section className="panel"><h2>Staff and inventory units</h2>{data.map(u=><article className="service" key={u.id}><h3>{u.id}</h3><p>{u.name} · {u.kind} · {u.active?'Active':'Unavailable'}</p><button onClick={()=>setUnit(structuredClone(u))}>Edit availability</button></article>)}<h3>Add a capacity pool</h3><label>Pool ID<input value={pool.id} onChange={e=>setPool({...pool,id:e.target.value})}/></label><label>Pool name<input value={pool.name} onChange={e=>setPool({...pool,name:e.target.value})}/></label><label>Type<select value={pool.kind} onChange={e=>setPool({...pool,kind:e.target.value})}><option value="inventory">Inventory</option><option value="concierge">Concierge staff</option></select></label><label>Number of units<input type="number" min="1" max="100" value={pool.count} onChange={e=>setPool({...pool,count:Number(e.target.value)})}/></label><small>New concierge units start off shift. Set shifts before publishing their service.</small><button disabled={busy||!pool.id||!pool.name} onClick={()=>run(()=>save('resources',{...pool,units:Array.from({length:pool.count},()=>({id:pool.id+'-'+crypto.randomUUID().slice(0,8),...(pool.kind==='concierge'?{shifts:weekly}:{})}))}))}>Add units</button></section><section className="panel"><h2>Unit availability</h2>{unit?<><h3>{unit.id}</h3><label className="agree"><input type="checkbox" checked={unit.active} onChange={e=>setUnit({...unit,active:e.target.checked})}/>Available for new reservations</label>{unit.kind==='concierge'&&shifts()}<button className="primary" disabled={busy} onClick={()=>run(async()=>{const r=await call('staff',unit);await load();setNotice(r.reviewAssignments.length?'Saved. Existing assignments need review: '+r.reviewAssignments.map((a:any)=>a.code??a.id).join(', '):'Availability saved.');})}>Save availability</button></>:<p>Select a unit to edit. Existing allocations stay reserved when availability changes.</p>}</section></div>}
 {tab==='tasks'&&<section className="panel"><h2>{who.role==='staff'?'Your assignments':'Concierge assignments'}</h2>{data.map(a=><article className="service" key={a.id}><h3>{a.code} · {a.service_name}</h3><p>{local(a.start_at)} → {local(a.end_at)}</p><p>{a.event_notes}</p><p>{a.guests} guests · {a.event_type} · {a.unit_id}</p>{who.role!=='staff'&&<label>Assigned staff<select value={a.unit_id} disabled={busy} onChange={e=>run(()=>save('assignments',{id:a.id,unitId:e.target.value}))}>{staff.filter(u=>u.kind==='concierge'&&(u.active||u.id===a.unit_id)).map(u=><option value={u.id} key={u.id}>{u.id}</option>)}</select></label>}<label>Task status<select value={a.fulfillment_status} onChange={e=>setData(data.map(v=>v.id===a.id?{...v,fulfillment_status:e.target.value}:v))}>{['assigned','started','completed','needs_help'].map(s=><option key={s}>{s}</option>)}</select></label><label>Handover notes<textarea maxLength={1000} value={a.notes} onChange={e=>setData(data.map(v=>v.id===a.id?{...v,notes:e.target.value}:v))}/></label><button disabled={busy} onClick={()=>run(()=>save('tasks',{id:a.id,status:a.fulfillment_status,notes:a.notes}))}>Save task update</button></article>)}{!data.length&&<p>No assigned concierge work.</p>}</section>}
 {tab==='bookings'&&<section className="panel"><h2>Bookings</h2>{data.map(b=><article className="service" key={b.id}><h3>{b.code} · {b.status}</h3><p>{b.space_id} · {local(b.start_at)} → {local(b.end_at)}</p><p>{b.customer.name} · {b.customer.email} · {b.customer.phone}</p><p>{b.customer.eventType} · {b.customer.notes}</p><p>{b.quote.guests} guests · {money(b.quote.totalSatang)}</p>{b.quote.items.map((item:any,i:number)=><div className="line" key={i}><span>{item.description}</span><strong>{money(item.totalSatang)}</strong></div>)}</article>)}</section>}
 {tab==='payments'&&<section className="panel"><h2>Payments & review queue</h2><p>Payment state comes from verified provider events. Review notes never mark a payment paid, issue a refund or release a reservation.</p>{data.map(p=><article className="service" key={p.id}><h3>{p.code} · {p.extension_id?'Extension':'Initial payment'} · {money(p.amount_satang)}</h3><p>{p.status} · {p.provider} · session {p.session_id}</p><small>Expires {local(p.expires_at)}</small><label>Review status<select value={p.review_status??'open'} onChange={e=>setData(data.map(v=>v.id===p.id?{...v,review_status:e.target.value}:v))}>{['open','investigating','resolved'].map(s=><option key={s}>{s}</option>)}</select></label><label>Reconciliation notes<textarea maxLength={1000} value={p.review_notes??''} onChange={e=>setData(data.map(v=>v.id===p.id?{...v,review_notes:e.target.value}:v))}/></label><button disabled={busy||!p.review_notes?.trim()} onClick={()=>run(()=>save('payment-reviews',{id:p.id,status:p.review_status??'open',notes:p.review_notes}))}>Save review</button></article>)}{!data.length&&<p>No payment records yet.</p>}</section>}
 {tab==='accounts'&&<section className="panel"><h2>Team access</h2><p>Only listed accounts can use their verified MFA session. Changes revoke existing app access until a new Access login. Team members must also be allowed in your Access policy.</p>{data.map(a=><article className="service" key={a.email}><h3>{a.email}</h3><p>{a.role} · {a.active?'Active':'Disabled'}</p><button onClick={()=>setAccount({email:a.email,role:a.role,unitId:a.unit_id??'',active:a.active})}>Edit access</button></article>)}<label>Email<input type="email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/></label><label>Role<select value={account.role} onChange={e=>setAccount({...account,role:e.target.value})}>{['owner','manager','staff'].map(s=><option key={s}>{s}</option>)}</select></label>{account.role==='staff'&&<label>Staff unit<select value={account.unitId} onChange={e=>setAccount({...account,unitId:e.target.value})}><option value="">Select concierge</option>{staff.filter(s=>s.kind==='concierge').map(s=><option key={s.id}>{s.id}</option>)}</select></label>}<label className="agree"><input type="checkbox" checked={account.active} onChange={e=>setAccount({...account,active:e.target.checked})}/>Account enabled</label><button disabled={busy||!account.email} onClick={()=>run(()=>save('accounts',account))}>Save team access</button></section>}
 {tab==='audit'&&<section className="panel"><h2>Audit history</h2>{data.map(a=><article key={a.id}><h3>{a.action}</h3><p>{a.actor} · {a.target} · {local(a.created_at)}</p></article>)}</section>}
 </>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="panel">{notice}</p>}</>}
 </main></>;
}
